#!/usr/bin/env bash
set -e

#
# Helpers
##################################################

red="\e[31m"
reset="\e[39m"

run() {
  task=${1}
  shift
  echo -e [${task}] ${@}
  ${@}
}

fail() {
  echo -e ${red}${@}${reset}
  exit 1
}

#
# Commands
##################################################

linkdir=node_modules/verdaccio-google-oauth-ui

#
# Remove the plugin from node_modules
#
clean() {
  run clean rm -rf .parcel-cache/ dist/ package/ plugins/
}

#
# Build server, config and client
#
build() {
  # bundle with parcel
  run build yarn parcel build --target client &
  run build yarn parcel build --target server &
  run build yarn parcel build --target cli &
  wait

  # add node shebang
  printf '%s\n%s\n' '#!/usr/bin/env node' "$(cat dist/cli/index.js)" > dist/cli/index.js
}

#
# Copy the built plugin to node_modules
#
copy() {
  run copy mkdir -p $pluginDir/
  run copy cp -R dist $pluginDir/
  run copy cp package.json $pluginDir/
}

typecheck() {
  run typecheck yarn tsc --noEmit --project src/client/tsconfig.json &
  run typecheck yarn tsc --noEmit --project src/server/tsconfig.json &
  run typecheck yarn tsc --noEmit --project src/cli/tsconfig.json &
  run typecheck yarn tsc --noEmit --project test/tsconfig.json &
  wait
}

readenv() {
  if [ -f .env ]; then
    set -a
    source .env
    set +a
  fi
}

#
# Sinopia CLI test
#
oauthclitest() {
  # npx verdaccio-google-oauth-ui --registry http://localhost:4873
  run clilogin ./dist/cli/index.js --registry http://localhost:4873
}

clilogin() {
  run clilogin ./dist/cli/index.js --registry http://localhost:4873
}

cliwhoami() {
  run cliwhoami npm whoami --registry http://localhost:4873
}

clipublish() {
  packageName="0.0.0-$(date +%Y%m%d%H%M%S)"
  directory="package/$packageName"

  run clipublish mkdir -p "$directory"
  echo "{\"name\":\"oauth-cli-test\",\"version\":\"$packageName\",\"license\":\"UNLICENSED\"}" > "$directory/package.json"
  run clipublish cd "$directory"
  run clipublish npm publish --registry http://localhost:4873
}

cli() {
  clilogin
  cliwhoami
  # clipublish
}

docker_() {
  readenv

  run docker docker rm --force verdaccio || true
  run docker docker build --tag verdaccio .
  run docker docker run \
    --publish 4873:4873 \
    --env "GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID" \
    --env "GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET" \
    --env "GITHUB_TOKEN=$GITHUB_TOKEN" \
    --name verdaccio verdaccio
}

#
# CLI
##################################################

#
# Call the function specified by the first parameter, passing all remaining
# parameters to the function. If no such function exists, display usage info.
#
if [ -n "$1" ] && type $1 | grep -i function > /dev/null; then
  command="$1"
  shift
  $command ${@}
else
  fail "No such command: $1"
fi
